/**
 * Everything a crawler and a link preview want, in one place, so no page can forget
 * half of it.
 *
 * The social card is a **static file** per page under `public/og`, generated by
 * `scripts/og.mjs`. A crawler often asks before the site has warmed up, and a file
 * cannot time out.
 */
/** Words this project is actually searched for. Site wide, so no page has to think. */
const KEYWORDS = [
  'nuxt',
  'nuxt module',
  'notifications',
  'messaging',
  'telegram bot',
  'discord webhook',
  'slack',
  'ntfy',
  'mastodon',
  'bluesky',
  'webhooks',
  'server sent events',
]

export function useDocsSeo(page: {
  title?: string
  description?: string
  path?: string
  keywords?: string[]
}) {
  const site = useRuntimeConfig().public.siteUrl
  const route = useRoute()

  const path = page.path ?? route.path
  const canonical = `${site}${path === '/' ? '' : path}`
  const title = page.title ?? 'nuxt-pigeon'
  const description = page.description ?? ''

  // `/channels/telegram` → `/og/channels-telegram.png`, and `/` → `/og/index.png`.
  const image = `${site}/og/${path === '/' ? 'index' : path.slice(1).replaceAll('/', '-')}.png`

  useSeoMeta({
    title,
    description,
    ogTitle: title,
    ogDescription: description,
    ogUrl: canonical,
    ogType: path === '/' ? 'website' : 'article',
    ogSiteName: 'nuxt-pigeon',
    ogLocale: 'en_US',
    ogImage: image,
    ogImageWidth: 1200,
    ogImageHeight: 630,
    ogImageType: 'image/png',
    ogImageAlt: title,
    twitterCard: 'summary_large_image',
    twitterTitle: title,
    twitterDescription: description,
    twitterImage: image,
    twitterImageAlt: title,
    // Google ignores keywords and has since 2009. Other engines and a few internal
    // site searches still read it, and it costs one tag.
    keywords: (page.keywords ?? KEYWORDS).join(', '),
    // The part that does have an effect: without it Google shows a thumbnail rather
    // than the full card.
    robots: 'index, follow, max-image-preview:large, max-snippet:-1, max-video-preview:-1',
    themeColor: '#0a0d33',
  })

  useHead({
    link: [{ rel: 'canonical', href: canonical }],
    script: [
      {
        type: 'application/ld+json',
        innerHTML: JSON.stringify({
          '@context': 'https://schema.org',
          '@type': path === '/' ? 'WebSite' : 'TechArticle',
          name: title,
          headline: title,
          description,
          url: canonical,
          image,
          inLanguage: 'en',
          isPartOf: { '@type': 'WebSite', name: 'nuxt-pigeon', url: site },
          about: {
            '@type': 'SoftwareSourceCode',
            name: 'nuxt-pigeon',
            programmingLanguage: 'TypeScript',
          },
          // Only on the landing page: this is what earns a search box under the
          // result in Google, and it is ignored anywhere else.
          ...(path === '/'
            ? {
                potentialAction: {
                  '@type': 'SearchAction',
                  target: { '@type': 'EntryPoint', urlTemplate: `${site}/?q={search_term_string}` },
                  'query-input': 'required name=search_term_string',
                },
              }
            : {}),
        }),
      },
      {
        // Breadcrumbs in the result, built from the path rather than repeated by hand.
        type: 'application/ld+json',
        innerHTML: JSON.stringify({
          '@context': 'https://schema.org',
          '@type': 'BreadcrumbList',
          itemListElement: [
            { '@type': 'ListItem', position: 1, name: 'nuxt-pigeon', item: site },
            ...path
              .split('/')
              .filter(Boolean)
              .map((part, index, parts) => ({
                '@type': 'ListItem',
                position: index + 2,
                name: part.replaceAll('-', ' ').replace(/^./, (c) => c.toUpperCase()),
                item: `${site}/${parts.slice(0, index + 1).join('/')}`,
              })),
          ],
        }),
      },
    ],
  })

  return { canonical, image }
}
